cfg4j/cfg4j

- .gitignore
- build.gradle
- src/main/java/pl/nort/ConfigurationService.java
- src/main/java/pl/nort/GitConfigurationService.java
- src/main/java/pl/nort/GitConfigurationServiceException.java
- src/test/java/pl/nort/GitConfigurationServiceIntegrationTest.java
- src/test/java/pl/nort/GitConfigurationServiceTest.java
> Simple git connector

- LICENSE
- README.md
- build.gradle
- src/main/java/pl/nort/ConfigurationService.java
- src/main/java/pl/nort/GitConfigurationService.java
- src/main/java/pl/nort/GitConfigurationServiceException.java
- src/test/java/pl/nort/GitConfigurationServiceIntegrationTest.java
- src/test/java/pl/nort/GitConfigurationServiceTest.java
> add Apache 2.0 license

- build.gradle
> Publish artifacts to maven central

- src/main/java/pl/nort/config/provider/ConfigurationProvider.java
- src/main/java/pl/nort/config/source/ConfigurationSource.java
- src/main/java/pl/nort/config/source/GitConfigurationSource.java
- src/test/java/pl/nort/config/provider/SimpleConfigurationProviderBindTest.java
- src/test/java/pl/nort/config/provider/SimpleConfigurationProviderGetPropertyTest.java
- src/test/java/pl/nort/config/source/GitConfigurationSourceIntegrationTest.java
> Manual refresh

- README.md
- src/main/java/pl/nort/config/provider/ConfigurationProviderBuilder.java
- src/main/java/pl/nort/config/source/EmptyConfigurationSource.java
- src/main/java/pl/nort/config/source/refresh/RefreshStrategy.java
- src/main/java/pl/nort/config/source/refresh/Refreshable.java
- src/main/java/pl/nort/config/source/refresh/strategy/NopRefreshStrategy.java
- src/main/java/pl/nort/config/source/refresh/strategy/OnInitRefreshStrategy.java
- src/main/java/pl/nort/config/source/refresh/strategy/PeriodicalRefreshStrategy.java
- src/test/java/pl/nort/config/provider/ConfigurationProviderBuilderTest.java
- src/test/java/pl/nort/config/source/EmptyConfigurationSourceTest.java
- src/test/java/pl/nort/config/source/refresh/strategy/NopRefreshStrategyTest.java
- src/test/java/pl/nort/config/source/refresh/strategy/OnInitRefreshStrategyTest.java
- src/test/java/pl/nort/config/source/refresh/strategy/PeriodicalRefreshStrategyTest.java
> Refresh strategy

- README.md
- build.gradle
- src/main/java/org/cfg4j/source/git/ConfigFilesProvider.java
- src/main/java/org/cfg4j/source/git/DefaultConfigFilesProvider.java
- src/main/java/org/cfg4j/source/git/GitConfigurationSource.java
- src/main/java/org/cfg4j/source/git/GitConfigurationSourceBuilder.java
- src/test/java/org/cfg4j/source/git/DefaultConfigFilesProviderTest.java
- src/test/java/org/cfg4j/source/git/GitConfigurationSourceIntegrationTest.java
> git: multiple configuration files support

- README.md
- build.gradle
- src/main/java/org/cfg4j/source/SourceCommunicationException.java
- src/main/java/org/cfg4j/source/consul/ConsulConfigurationSource.java
- src/main/java/org/cfg4j/source/git/GitConfigurationSource.java
- src/test/java/org/cfg4j/source/consul/ConsulConfigurationSourceIntegrationTest.java
> Consul adapter

- src/main/java/org/cfg4j/source/refresh/strategy/PeriodicalRefreshStrategy.java
- src/test/java/org/cfg4j/source/refresh/strategy/PeriodicalRefreshStrategyTest.java
> use TimeUnit when constructing PeriodicalRefreshStrategy

- src/main/java/org/cfg4j/source/ConfigurationSource.java
- src/main/java/org/cfg4j/source/compose/MergeConfigurationSource.java
- src/test/java/org/cfg4j/source/compose/MergeConfigurationSourceTest.java
- src/test/java/org/cfg4j/source/consul/ConsulConfigurationSourceIntegrationTest.java
> Configuration merging

- build.gradle
- src/main/java/org/cfg4j/provider/SimpleConfigurationProvider.java
- src/main/java/org/cfg4j/source/context/ImmutableEnvironment.java
- src/main/java/org/cfg4j/source/git/DefaultConfigFilesProvider.java
- src/main/java/org/cfg4j/source/git/GitConfigurationSource.java
- src/main/java/org/cfg4j/source/refresh/strategy/PeriodicalRefreshStrategy.java
- src/test/java/org/cfg4j/source/git/GitConfigurationSourceIntegrationTest.java
- src/test/java/org/cfg4j/source/git/TempConfigurationGitRepo.java
- src/test/java/org/cfg4j/validator/BindingValidatorTest.java
> remove guava dependency

- src/main/java/org/cfg4j/source/compose/FallbackConfigurationSource.java
- src/main/java/org/cfg4j/source/compose/MergeConfigurationSource.java
- src/main/java/org/cfg4j/source/context/MissingEnvironmentException.java
- src/main/java/org/cfg4j/source/refresh/Refreshable.java
- src/test/java/org/cfg4j/source/compose/FallbackConfigurationSourceTest.java
> Fallback mechanism

- src/main/java/org/cfg4j/source/consul/ConsulConfigurationSource.java
- src/main/java/org/cfg4j/source/files/FilesConfigurationSource.java
- src/test/java/org/cfg4j/source/files/FilesConfigurationSourceTest.java
- src/test/java/org/cfg4j/source/files/TempConfigurationFileRepo.java
- src/test/java/org/cfg4j/source/git/GitConfigurationSourceIntegrationTest.java
- src/test/java/org/cfg4j/source/git/TempConfigurationGitRepo.java
> File system adapter

- src/main/java/org/cfg4j/source/classpath/ClasspathConfigurationSource.java
- src/main/java/org/cfg4j/source/files/FilesConfigurationSource.java
- src/main/java/org/cfg4j/source/git/GitConfigurationSource.java
- src/test/java/org/cfg4j/source/classpath/ClasspathConfigurationSourceTest.java
- src/test/java/org/cfg4j/source/classpath/TempConfigurationClasspathRepo.java
- src/test/java/org/cfg4j/source/files/FilesConfigurationSourceTest.java
- src/test/java/org/cfg4j/source/files/TempConfigurationFileRepo.java
- src/test/java/org/cfg4j/source/git/GitConfigurationSourceIntegrationTest.java
- src/test/resources/application.properties
- src/test/resources/malformed.properties
- src/test/resources/otherApplicationConfigs/application.properties
- src/test/resources/otherConfig.properties
> Classpath source

- cfg4j-core/src/main/java/org/cfg4j/source/files/FilesConfigurationSource.java
- cfg4j-core/src/test/java/org/cfg4j/source/files/FilesConfigurationSourceTest.java
> Better files paths resolution

- cfg4j-consul/src/main/java/org/cfg4j/source/consul/ConsulConfigurationSource.java
- cfg4j-core/src/main/java/org/cfg4j/provider/ConfigurationProviderBuilder.java
- cfg4j-core/src/main/java/org/cfg4j/provider/GenericType.java
- cfg4j-core/src/main/java/org/cfg4j/provider/SimpleConfigurationProvider.java
- cfg4j-core/src/main/java/org/cfg4j/source/DefaultConfigFilesProvider.java
- cfg4j-core/src/main/java/org/cfg4j/source/EmptyConfigurationSource.java
- cfg4j-core/src/main/java/org/cfg4j/source/classpath/ClasspathConfigurationSource.java
- cfg4j-core/src/main/java/org/cfg4j/source/compose/FallbackConfigurationSource.java
- cfg4j-core/src/main/java/org/cfg4j/source/compose/MergeConfigurationSource.java
- cfg4j-core/src/main/java/org/cfg4j/source/context/DefaultEnvironment.java
- cfg4j-core/src/main/java/org/cfg4j/source/context/ImmutableEnvironment.java
- cfg4j-core/src/main/java/org/cfg4j/source/files/FilesConfigurationSource.java
- cfg4j-core/src/main/java/org/cfg4j/source/refresh/strategy/OnInitReloadStrategy.java
- cfg4j-core/src/main/java/org/cfg4j/source/refresh/strategy/PeriodicalReloadStrategy.java
- cfg4j-git/src/main/java/org/cfg4j/source/git/GitConfigurationSource.java
- cfg4j-git/src/main/java/org/cfg4j/source/git/GitConfigurationSourceBuilder.java
> Improved toString

- cfg4j-core/src/main/java/org/cfg4j/provider/ConfigurationProviderBuilder.java
- cfg4j-core/src/main/java/org/cfg4j/source/reload/ReloadStrategy.java
- cfg4j-core/src/main/java/org/cfg4j/source/reload/Reloadable.java
- cfg4j-core/src/main/java/org/cfg4j/source/reload/strategy/ImmediateReloadStrategy.java
- cfg4j-core/src/main/java/org/cfg4j/source/reload/strategy/OnInitReloadStrategy.java
- cfg4j-core/src/main/java/org/cfg4j/source/reload/strategy/PeriodicalReloadStrategy.java
- cfg4j-core/src/test/java/org/cfg4j/provider/ConfigurationProviderBuilderTest.java
- cfg4j-core/src/test/java/org/cfg4j/source/reload/strategy/ImmediateReloadStrategyTest.java
- cfg4j-core/src/test/java/org/cfg4j/source/reload/strategy/PeriodicalReloadStrategyTest.java
> Better reload strategy

- cfg4j-core/src/main/java/org/cfg4j/provider/SimpleConfigurationProvider.java
- cfg4j-core/src/test/java/org/cfg4j/provider/SimpleConfigurationProviderIntegrationTest.java
- cfg4j-core/src/test/resources/org/cfg4j/provider/SimpleConfigurationProviderIntegrationTest_shouldReadYamlBooleans.yaml
- cfg4j-core/src/test/resources/org/cfg4j/provider/SimpleConfigurationProviderIntegrationTest_shouldReadYamlIntegers.yaml
> Yaml non-string fix

- cfg4j-core/src/main/java/org/cfg4j/provider/BindInvocationHandler.java
- cfg4j-core/src/test/java/org/cfg4j/provider/BindInvocationHandlerTest.java
> BindInvocationHandler fix

- README.md
- build.gradle
- cfg4j-core/src/main/java/org/cfg4j/provider/ConfigurationProvider.java
- cfg4j-core/src/main/java/org/cfg4j/provider/ConfigurationProviderBuilder.java
- cfg4j-core/src/main/java/org/cfg4j/provider/MeteredConfigurationProvider.java
- cfg4j-core/src/main/java/org/cfg4j/provider/SimpleConfigurationProvider.java
- cfg4j-core/src/main/java/org/cfg4j/source/metered/MeteredConfigurationSource.java
- cfg4j-core/src/test/java/org/cfg4j/provider/MeteredConfigurationProviderTest.java
- cfg4j-core/src/test/java/org/cfg4j/source/metered/MeteredConfigurationSourceTest.java
- cfg4j-core/src/test/java/org/cfg4j/source/reload/strategy/PeriodicalReloadStrategyTest.java
> Add metrics support

- cfg4j-consul/src/main/java/org/cfg4j/source/consul/ConsulConfigurationSource.java
- cfg4j-consul/src/test/java/org/cfg4j/source/consul/ConsulConfigurationSourceIntegrationTest.java
- cfg4j-core/src/main/java/org/cfg4j/source/ConfigurationSource.java
- cfg4j-core/src/main/java/org/cfg4j/source/classpath/ClasspathConfigurationSource.java
- cfg4j-core/src/main/java/org/cfg4j/source/compose/FallbackConfigurationSource.java
- cfg4j-core/src/main/java/org/cfg4j/source/compose/MergeConfigurationSource.java
- cfg4j-core/src/main/java/org/cfg4j/source/empty/EmptyConfigurationSource.java
- cfg4j-core/src/main/java/org/cfg4j/source/files/FilesConfigurationSource.java
- cfg4j-core/src/main/java/org/cfg4j/source/metered/MeteredConfigurationSource.java
- cfg4j-core/src/test/java/org/cfg4j/source/classpath/ClasspathConfigurationSourceTest.java
- cfg4j-core/src/test/java/org/cfg4j/source/compose/FallbackConfigurationSourceTest.java
- cfg4j-core/src/test/java/org/cfg4j/source/compose/MergeConfigurationSourceTest.java
- cfg4j-core/src/test/java/org/cfg4j/source/empty/EmptyConfigurationSourceTest.java
- cfg4j-core/src/test/java/org/cfg4j/source/files/FilesConfigurationSourceTest.java
- cfg4j-core/src/test/java/org/cfg4j/source/metered/MeteredConfigurationSourceTest.java
- cfg4j-git/src/main/java/org/cfg4j/source/git/GitConfigurationSource.java
- cfg4j-git/src/test/java/org/cfg4j/source/git/GitConfigurationSourceIntegrationTest.java
> Configurationsource init

- cfg4j-consul/src/test/java/org/cfg4j/source/consul/SimpleConfigurationProviderIntegrationTest.java
- cfg4j-core/src/main/java/org/cfg4j/provider/ConfigurationProviderBuilder.java
- cfg4j-core/src/main/java/org/cfg4j/source/inmemory/InMemoryConfigurationSource.java
- cfg4j-core/src/test/java/org/cfg4j/provider/SimpleConfigurationProviderWithClasspathIntegrationTest.java
- cfg4j-core/src/test/java/org/cfg4j/provider/SimpleConfigurationProviderWithMeteredSourceIntegrationTest.java
- cfg4j-core/src/test/java/org/cfg4j/source/inmemory/InMemoryConfigurationSourceTest.java
- cfg4j-git/src/test/java/org/cfg4j/source/git/SimpleConfigurationProviderIntegrationTest.java
- ConfigurationProvider integration tests (with different sources)
- new in-memory source - fixes #119, fixes #9
> Integration tests

- build.gradle
- cfg4j-core/src/main/java/org/cfg4j/provider/BindInvocationHandler.java
- cfg4j-core/src/main/java/org/cfg4j/source/classpath/ClasspathConfigurationSource.java
- cfg4j-core/src/main/java/org/cfg4j/source/files/FilesConfigurationSource.java
- cfg4j-core/src/main/java/org/cfg4j/source/reload/strategy/PeriodicalReloadStrategy.java
- cfg4j-git/src/main/java/org/cfg4j/source/git/GitConfigurationSource.java
> Java 7 compatibility

- cfg4j-consul/src/main/java/org/cfg4j/source/consul/ConsulConfigurationSource.java
- cfg4j-consul/src/test/java/org/cfg4j/source/consul/ConsulConfigurationSourceIntegrationTest.java
- cfg4j-git/src/main/java/org/cfg4j/source/git/GitConfigurationSource.java
- cfg4j-git/src/test/java/org/cfg4j/source/git/GitConfigurationSourceIntegrationTest.java
> Fail safe for get configuration

- cfg4j-consul/src/main/java/org/cfg4j/source/consul/ConsulConfigurationSource.java
> Use builder() instead of depricated newClient() method

- build.gradle
- cfg4j-core/src/main/java/org/cfg4j/source/system/EnvironmentVariablesConfigurationSource.java
- cfg4j-core/src/test/java/org/cfg4j/source/system/EnvironmentVariablesConfigurationSourceTest.java
Related to #128 provides an implementation for loading from System OS Environment Variables
> Load config from System OS Environment Variables

- cfg4j-core/src/main/java/org/cfg4j/provider/ConfigurationProviderBuilder.java
- cfg4j-core/src/main/java/org/cfg4j/source/metered/MeteredConfigurationSource.java
- cfg4j-core/src/main/java/org/cfg4j/source/reload/MeteredReloadable.java
- cfg4j-core/src/test/java/org/cfg4j/provider/BindInvocationHandlerTest.java
- cfg4j-core/src/test/java/org/cfg4j/provider/SimpleConfigurationProviderWithMeteredSourceIntegrationTest.java
- cfg4j-core/src/test/java/org/cfg4j/source/metered/MeteredConfigurationSourceTest.java
- cfg4j-core/src/test/java/org/cfg4j/source/reload/MeteredReloadableTest.java
- cfg4j-core/src/test/java/org/cfg4j/validator/BindingValidatorTest.java
This is a follow-up to the suggestion made by @majkiw in #148.
- Add back the option to monitor execution time of reload() method.
> Metered reloadable
